# Generated by Django 5.0.2 on 2024-06-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0002_alter_productbought_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttobuy",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_intentions",
                to="shopping_list.product",
            ),
        ),
    ]
