# Generated by Django 5.0.2 on 2024-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0003_alter_producttobuy_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbought",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
