# Generated by Django 5.0.2 on 2024-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
