# Generated by Django 5.0.2 on 2024-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='join_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
