# Generated by Django 5.0.2 on 2024-06-05 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household_chores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SelectableTask",
            new_name="AssignableTask",
        ),
    ]
