# Generated by Django 5.0.2 on 2024-06-06 09:31

import household_chores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household_chores", "0002_rename_selectabletask_assignabletask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignabletask",
            name="date",
            field=models.DateField(default=household_chores.models.get_default_date),
        ),
    ]
