# Generated by Django 5.0.2 on 2024-05-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_distribution", "0001_initial"),
        ("groups", "0003_group_join_code_group_join_code_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="groups.group",
            ),
        ),
    ]
