# Generated by Django 5.0.2 on 2024-06-03 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_distribution", "0002_alter_expense_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_paid",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
