# Generated by Django 5.0.2 on 2024-06-05 14:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_distribution", "0003_alter_expense_date_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 5, 14, 47, 56, 356151, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
