# Generated by Django 5.0.2 on 2024-06-05 15:06

import expense_distribution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_distribution", "0004_alter_expense_date_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_paid",
            field=models.DateField(default=expense_distribution.models.current_date),
        ),
    ]
