# Generated by Django 5.0.2 on 2024-05-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedBoard',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField(
                     blank=True)),
                ('last_edited',
                 models.DateTimeField(
                     auto_now=True)),
                ('group',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='auth.group')),
            ],
        ),
    ]
