# Generated by Django 5.0.2 on 2024-05-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_join_code_group_join_code_expiration"),
        ("shared_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedboard",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="groups.group"
            ),
        ),
    ]
