# Generated by Django 5.0.2 on 2024-04-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token_expiration',
        ),
    ]
