# Generated by Django 5.0.2 on 2024-04-07 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userprofile_token_expiration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="UserTokenResetPassword",
        ),
    ]
